titulo: Soccer International Agents
email: info@soccerintagents.com
descripcion: Soccer international agents, soccer agents, football agents
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://soccerintagents.com" # the base hostname & protocol for your site, e.g. http://example.com

sass:
  sass_dir: css
  style: compressed	

# Build settings
markdown: kramdown
theme: minima
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  jugadores:
